# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-01 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=2, upload_to=b'img'),
            preserve_default=False,
        ),
    ]
